project_id = "ehqdxlqaqmcqnwtlovhw"

[functions.ebay-marketplace-account-deletion]
verify_jwt = false

[functions.fetch-card-pricing]
verify_jwt = true

[functions.process-pricing-queue]
verify_jwt = false

[functions.refresh-top-cards]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-reminder-emails]
verify_jwt = false

[functions.send-quick-reminder]
verify_jwt = false

[functions.send-first-save-email]
verify_jwt = false

[functions.test-send-emails]
verify_jwt = false

[functions.detect-items]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.process-payment]
verify_jwt = true